"""Create transcription_jobs table

Revision ID: d8fc8cf22a91
Revises:
Create Date: 2026-06-23 15:43:41.674349

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd8fc8cf22a91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'transcription_jobs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('stored_audio_path', sa.String(length=512), nullable=False),
        sa.Column('content_type', sa.String(length=255), nullable=True),
        sa.Column('file_size_bytes', sa.Integer(), nullable=False),
        sa.Column('language', sa.String(length=10), nullable=True),
        sa.Column('text', sa.Text(), nullable=True),
        sa.Column('error_message', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_transcription_jobs_created_at',
        'transcription_jobs',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        'ix_transcription_jobs_status',
        'transcription_jobs',
        ['status'],
        unique=False,
    )
    op.create_index(
        'ix_transcription_jobs_status_created_at',
        'transcription_jobs',
        ['status', 'created_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_transcription_jobs_status_created_at',
        table_name='transcription_jobs',
    )
    op.drop_index(
        'ix_transcription_jobs_status', table_name='transcription_jobs'
    )
    op.drop_index(
        'ix_transcription_jobs_created_at', table_name='transcription_jobs'
    )
    op.drop_table('transcription_jobs')
    # ### end Alembic commands ###
